name: Run

on:
  workflow_dispatch:

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up environment
        run: |
          GO_VERSION=`sed -n '3p' go.mod | awk '{print $2}'`
          echo "GO_VERSION=${GO_VERSION}" >> $GITHUB_ENV

      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: ${{ env.GO_VERSION }}

      - name: Run Punchcard
        run: go run .
        env:
          TZ: "Asia/Jakarta"

      - name: Set commit message as environment variable
        run: |
          NOW=$(date '+%Y-%m-%d')
          echo "COMMIT_MESSAGE=Punchcard as of $NOW" >> $GITHUB_ENV

      - name: Commit changes and push them to GitHub
        uses: EndBug/add-and-commit@v9
        with:
          add: "data"
          author_name: ${{ secrets.GIT_AUTHOR_NAME }}
          author_email: ${{ secrets.GIT_AUTHOR_EMAIL }}
          message: ${{ env.COMMIT_MESSAGE }}
